My display events
Bruin-Entrepreneurs/be_socialApp pull request #1
Opened 2018-02-21 07:54 UTC by michaelnyu

Added a components folder which holds both components and styles for each component.  Added an EVENTITEM component and a EVENTLIST component.  Set up modular style sheets and a clobal style sheet ( commonstyles.js ).  Cleaned up some of the spacing issues in App.js.  Implemented a displayEvents page in App.js.  (unsure of whether to branch each view into a separate container)

2018-02-23 23:16 UTC, epicchewy requested changes

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +      	}
nit: tab

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +	constructor() {
format: 2-space tabs

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +		let eventsArray = this.state.eventsArray;
use const for immutable

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +		uri: 'https://pbs.twimg.com/profile_images/862164234947440640/WqQ358Yw_400x400.jpg'
tab

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +			  		else{
put else on same line

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +class DisplayEventsScreen extends React.Component {
one component per file? i feel like its easier to maintain that way

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +		let {eventsArray} = this.props.navigation.state.params;
const { eventsArray }

2018-02-23 23:16 UTC, epicchewy commented on App.js
> +			 <TextInput style={{height: 40, width: 200, borderColor: 'black', borderWidth: 2, }}  value={this.state.inputText} onChangeText={(text) => this.setState({ inputText: text })} />
no parentheses for single argument arrow functions `onChangeTest={text => ... }`

2018-02-23 23:16 UTC, epicchewy commented on App.js
>  export default App;
nit: new line

2018-02-23 23:16 UTC, epicchewy commented on commonstyles.js
> +export const BORDER_RADIUS = 5;
nit: new line

2018-02-23 23:16 UTC, epicchewy commented on components/eventitem.js
> +    Text, View, TouchableHighlight
just a note: try to be consistent with when you use multiline imports. use your best judgement for when the import is too long/unreadable

2018-02-23 23:16 UTC, epicchewy commented on components/eventitemstyle.js
> +});
nit: new line

2018-02-23 23:16 UTC, epicchewy commented on components/eventitem.js
> +import styles from './eventitemstyle';
move all styling to its own folder /components/style, /style or something like that

2018-02-23 23:16 UTC, epicchewy commented on components/eventliststyles.js
> +});
nit: new line

2018-02-23 23:16 UTC, epicchewy commented on components/eventitemstyle.js
> +export default StyleSheet.create({
add line above export

2018-02-23 23:17 UTC, epicchewy commented on App.js
> +   			eventsArray: ["events1", "events2"],
move dummy data somewhere else

2018-02-27 18:12 UTC, epicchewy requested changes
much better, but lets try to remain consistent with style throughout the entire repo

2018-02-27 18:12 UTC, epicchewy commented on App.js
> +	},
can we export this dummy data to another file?

2018-02-27 18:12 UTC, epicchewy commented on App.js
> +		return (
new line here for readability

2018-02-27 18:12 UTC, epicchewy commented on App.js
> +				<Button onPress={() => {
not sure if the () are optional or not for 0 argument lambda

2018-02-27 18:12 UTC, epicchewy commented on App.js
>  let pic2 = {
two space indents? that is the js standard

2018-02-27 18:12 UTC, epicchewy commented on App.js
> +		return (
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on App.js
>  const styles = StyleSheet.create({
is it standard practice to keep styles and view together for react native? if not, lets keep them decoupled

2018-02-27 18:12 UTC, epicchewy commented on common_styles.js
> +export const BORDER_RADIUS = 5;
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on App.js
>  					onPress={(person) => this.setState({ namesArray: [...this.state.namesArray, l.name, ', '] })}
no parentheses around single argument double arrow functions

2018-02-27 18:12 UTC, epicchewy commented on components/event_item.js
> +    render() {
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on components/event_item.js
> +module.exports = EventItem;
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on components/event_list.js
> +            {eventsArray.map((event, i) =>
nit: indent this block

2018-02-27 18:12 UTC, epicchewy commented on components/styles/event_item_style.js
> +);
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on components/styles/event_list_styles.js
> +);
nit: new line

2018-02-27 18:12 UTC, epicchewy commented on screens/DisplayEventsScreen.js
> +		let { eventsArray } = this.props.navigation.state.params;
const here?

2018-02-27 18:12 UTC, epicchewy commented on screens/NavigationBar.js
> +          onPress={() => this.setState({
same as above

2018-02-27 18:12 UTC, epicchewy commented on screens/NavigationBar.js
> +          onPress={() => this.setState({
same as above

2018-02-27 18:12 UTC, epicchewy commented on screens/NavigationBar.js
> +NavigationExampleScreen.contextTypes = contextTypes;
nit: new line

2018-02-27 18:59 UTC, michaelnyu commented on App.js
> +				<Button onPress={() => {
it is

2018-02-27 19:00 UTC, michaelnyu commented on App.js
>  let pic2 = {
change all files to be a two space indent?

2018-02-27 19:40 UTC, epicchewy commented on App.js
>  let pic2 = {
yes

2018-02-27 20:20 UTC, michaelnyu commented on common_styles.js
> +export const BORDER_RADIUS = 5;
what does nit mean

2018-02-27 20:44 UTC, michaelnyu commented on App.js
>  const styles = StyleSheet.create({
i agree

2018-02-27 21:46 UTC, epicchewy commented on App.js
> +				<Button onPress={() => {
if they're optional, lets remove them to be `{ => { ... }}`

2018-02-27 21:47 UTC, epicchewy commented on common_styles.js
> +export const BORDER_RADIUS = 5;
nit pick

2018-02-28 02:48 UTC, michaelnyu commented on App.js
> +				<Button onPress={() => {
i meant it is necessary.  my b

2018-03-07 06:35 UTC, closed without merging