My/button
Bruin-Entrepreneurs/be_socialApp pull request #2
Opened 2018-04-02 22:16 UTC by michaelnyu

includes some of fb/auth commits. namely the reorganization of files.

2018-04-02 23:08 UTC, epicchewy requested changes

2018-04-02 23:08 UTC, epicchewy commented on data.js
> +import { Image, } from 'react-native';
remove unused import

2018-04-02 23:08 UTC, epicchewy commented on package.json
> +    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
should use latest version number

2018-04-02 23:08 UTC, epicchewy commented on App.js
> +import UserProfile from './src/screens/UserProfile';
add new line to differentiate between external packages and project modules

2018-04-02 23:08 UTC, epicchewy commented on App.js
> +import InviteScreen from './src/screens/InviteScreen';
nit: alphabetize imports for readability

2018-04-02 23:08 UTC, epicchewy commented on App.js
> +var {height, width} = Dimensions.get('window');
remove unused

2018-04-02 23:08 UTC, epicchewy commented on App.js
> +//------------------------------------------------------
what is the purpose of this comment? 
if it is to break up stylesheets, say something like General Styling, X-Component Styling, etc.

2018-04-02 23:08 UTC, epicchewy commented on README.md
> +# BE SOCIAL APP
Add project description, setup instructions, any other important information

2018-04-02 23:08 UTC, epicchewy commented on App.js
> +	Home: { screen: HomeView},
{ screen: HomeView }

2018-04-02 23:08 UTC, epicchewy commented on data.js
> +import React from 'react';
remove unused import

2018-04-02 23:08 UTC, epicchewy commented on data.js
> +const event_types = [
remove unexported array or export it

2018-04-02 23:08 UTC, epicchewy commented on src/components/Button.js
> +	const k_container = [styles.full];
nit: new line after

2018-04-02 23:08 UTC, epicchewy commented on src/components/Button.js
> +	const k_container = [styles.full];
camelcast kContainer
add comment, what does kContainer do?

2018-04-02 23:08 UTC, epicchewy commented on src/components/CardList.js
> +import React from 'react';
remove unused import

2018-04-02 23:08 UTC, epicchewy commented on src/components/CardList.js
> +import { Card, } from 'react-native-elements';
i personally dont like the training comma in imports, but its up to you

2018-04-02 23:08 UTC, epicchewy commented on App.js
>  import React from 'react';
remove unused import

2018-04-02 23:08 UTC, epicchewy commented on src/components/CardList.js
> +	console.log(styles.eventContainer)
remove log

2018-04-02 23:08 UTC, epicchewy commented on src/components/styles/ButtonStyle.js
> +    borderColor: "transparent",
alignment

2018-04-02 23:08 UTC, epicchewy commented on src/components/styles/ButtonStyle.js
> +import React, { StyleSheet } from 'react-native';
remove React

2018-04-02 23:08 UTC, epicchewy commented on src/components/styles/CardListStyle.js
> +import React, { StyleSheet } from 'react-native';
remove React

2018-04-02 23:08 UTC, epicchewy commented on src/constants/styles.js
> +export const BORDER_RADIUS = 5;
new line

2018-04-02 23:08 UTC, epicchewy commented on src/constants/styles.js
> +import { Alert, DatePickerIOS, StyleSheet, Text, View, AppRegistry, Image, TextInput, Picker, Dimensions } from 'react-native';
import {
  Alert,
  DatePicker,
  ...

2018-04-02 23:08 UTC, epicchewy commented on src/constants/styles.js
> +import React from 'react';
remove

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +import Button from '../components/Button';
new line, separation of concerns

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +var moment = require('moment');
const

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +var idLocale = require('moment/locale/id');
const

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +		let typeFields = [
where is this data coming from

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +const styles = StyleSheet.create({
move to different file

2018-04-02 23:08 UTC, epicchewy commented on src/screens/CreationScreen.js
> +});
nit: new line

2018-04-02 23:08 UTC, epicchewy commented on src/screens/EventScreen.js
> +import { Card, } from 'react-native-elements';
remove unused

2018-04-02 23:08 UTC, epicchewy commented on src/screens/EventScreen.js
> +import { StackNavigator, } from 'react-navigation';
remove unused

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +var {height, width} = Dimensions.get('window');
const

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +import { CardList } from 'react-native-card-list';
nit: new line

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +				flexDirection: 'column',
indent

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +			textInputVal: 'username',
what is the purpose of setting this state here

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +					<Image source={require('../../assets/BE.png')} style={styles.picture} />
move require above as import

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +				<View style={{backgroundColor: '#b2d8d8', flex: 0.6}}>
there should be no hard-coded hex values in components, move to style constants file

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +const styles = StyleSheet.create({
move styles out

2018-04-02 23:08 UTC, epicchewy commented on src/screens/HomeScreen.js
> +
remove extra new lines

2018-04-02 23:08 UTC, epicchewy commented on src/screens/InviteScreen.js
> +var moment = require('moment');
same as above

2018-04-02 23:08 UTC, epicchewy commented on src/screens/InviteScreen.js
> +let allNames = [
move dummy data to separate file

2018-04-02 23:08 UTC, epicchewy commented on src/screens/InviteScreen.js
> +	makePostRequest() {
do not commit method if not implemented

2018-04-02 23:08 UTC, epicchewy commented on src/screens/InviteScreen.js
> +		const { navigate } = this.props.navigation;
new line

2018-04-02 23:08 UTC, epicchewy commented on src/screens/InviteScreen.js
> +const styles = StyleSheet.create({
move out

2018-04-02 23:08 UTC, epicchewy commented on src/screens/UserProfile.js
> +import { StackNavigator, } from 'react-navigation';
new line, separation of concerns

2018-04-02 23:08 UTC, epicchewy commented on src/screens/UserProfile.js
> +			imageURL: 'https://pbs.twimg.com/profile_images/862164234947440640/WqQ358Yw_400x400.jpg',
move url out as enum or use other import

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles.js
> +import { Alert, DatePickerIOS, StyleSheet, Text, View, AppRegistry, Image, TextInput, Picker, Dimensions } from 'react-native';
same as above

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles.js
> +import React from 'react';
same as above

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles.js
> +
remove unused imports

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles.js
> +});
new line

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles/UserProfileStyle.js
> +import React, { StyleSheet } from 'react-native';
remove

2018-04-02 23:08 UTC, epicchewy commented on src/screens/styles/UserProfileStyle.js
> +	},
alignment

2018-04-02 23:08 UTC, epicchewy commented on .watchmanconfig
> -{}
whats the point of this file? if theres no purpose, delete

2018-04-02 23:08 UTC, epicchewy commented on App.js
remove extra lines until there is only one

2018-04-02 23:08 UTC, epicchewy commented on src/components/styles/CardListStyle.js
> +})
add ;

2018-04-02 23:10 UTC, epicchewy commented
Couple more things to address:
1. Be very careful about updating packages moving forward. If there is a diff on the package-lock file, commit immediately if you're adding, inform others if you update
2. Drop a couple of screenshots/detailed description of UI update, so that others know exactly what your change is.

2018-04-03 01:35 UTC, michaelnyu commented on .watchmanconfig
> -{}
I think i removed it from the commit.  I'm not really sure how to check that however

2018-04-03 01:38 UTC, michaelnyu commented on package.json
> +    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
not sure what this means.  I wasn't the one who changed this i think

2018-04-03 02:04 UTC, michaelnyu commented on App.js
> +import UserProfile from './src/screens/UserProfile';
done

2018-04-03 02:04 UTC, michaelnyu commented on App.js
> +import InviteScreen from './src/screens/InviteScreen';
done

2018-04-03 02:05 UTC, michaelnyu commented on README.md
> +# BE SOCIAL APP
done

2018-04-03 02:20 UTC, michaelnyu commented on App.js
> +	Home: { screen: HomeView},
doe

2018-04-03 02:21 UTC, michaelnyu commented on src/components/Button.js
> +	const k_container = [styles.full];
done

2018-04-03 02:21 UTC, michaelnyu commented on src/components/Button.js
> +	const k_container = [styles.full];
done

2018-04-03 02:21 UTC, michaelnyu commented on src/components/CardList.js
> +import React from 'react';
done

2018-04-03 02:22 UTC, michaelnyu commented on src/components/CardList.js
> +import { Card, } from 'react-native-elements';
looks kinda weird when its a single line. i agree

2018-04-03 02:22 UTC, michaelnyu commented on App.js
>  import React from 'react';
done

2018-04-03 02:22 UTC, michaelnyu commented on src/components/CardList.js
> +	console.log(styles.eventContainer)
done

2018-04-03 02:23 UTC, michaelnyu commented on src/components/styles/ButtonStyle.js
> +    borderColor: "transparent",
done

2018-04-03 02:23 UTC, michaelnyu commented on src/components/styles/ButtonStyle.js
> +import React, { StyleSheet } from 'react-native';
done

2018-04-03 02:23 UTC, michaelnyu commented on src/components/styles/CardListStyle.js
> +import React, { StyleSheet } from 'react-native';
done

2018-04-03 02:23 UTC, michaelnyu commented on src/constants/styles.js
> +export const BORDER_RADIUS = 5;
done

2018-04-03 02:23 UTC, michaelnyu commented on src/constants/styles.js
> +import { Alert, DatePickerIOS, StyleSheet, Text, View, AppRegistry, Image, TextInput, Picker, Dimensions } from 'react-native';
done

2018-04-03 02:24 UTC, michaelnyu commented on src/constants/styles.js
> +import { Alert, DatePickerIOS, StyleSheet, Text, View, AppRegistry, Image, TextInput, Picker, Dimensions } from 'react-native';
removed all

2018-04-03 02:24 UTC, michaelnyu commented on src/constants/styles.js
> +import React from 'react';
done

2018-04-03 02:25 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +import Button from '../components/Button';
done

2018-04-03 02:26 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +var moment = require('moment');
done

2018-04-03 02:26 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +var idLocale = require('moment/locale/id');
done

2018-04-03 02:27 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +		let typeFields = [
i believe it is unnecessary list that i forgot to delete

2018-04-03 02:28 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +const styles = StyleSheet.create({
done

2018-04-03 02:30 UTC, michaelnyu commented on src/screens/CreationScreen.js
> +});
done

2018-04-03 02:31 UTC, michaelnyu commented on src/screens/EventScreen.js
> +import { Card, } from 'react-native-elements';
done

2018-04-03 02:31 UTC, michaelnyu commented on src/screens/EventScreen.js
> +import { StackNavigator, } from 'react-navigation';
done

2018-04-03 02:32 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +var {height, width} = Dimensions.get('window');
done

2018-04-03 02:33 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +import { CardList } from 'react-native-card-list';
done

2018-04-03 02:33 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +				flexDirection: 'column',
done

2018-04-03 02:34 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +			textInputVal: 'username',
unecessary.  But, this whole portion will be replace by fb login. fixed anyways

2018-04-03 02:35 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +					<Image source={require('../../assets/BE.png')} style={styles.picture} />
done

2018-04-03 03:12 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +				<View style={{backgroundColor: '#b2d8d8', flex: 0.6}}>
done

2018-04-03 03:13 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +const styles = StyleSheet.create({
done

2018-04-03 03:18 UTC, michaelnyu commented on src/screens/HomeScreen.js
> +
done

2018-04-03 03:19 UTC, michaelnyu commented on src/screens/InviteScreen.js
> +var moment = require('moment');
done

2018-04-03 03:19 UTC, michaelnyu commented on src/screens/InviteScreen.js
> +let allNames = [
done

2018-04-03 03:19 UTC, michaelnyu commented on src/screens/InviteScreen.js
> +	makePostRequest() {
okay

2018-04-03 03:19 UTC, michaelnyu commented on src/screens/InviteScreen.js
> +		const { navigate } = this.props.navigation;
done

2018-04-03 04:42 UTC, michaelnyu commented on src/screens/InviteScreen.js
> +const styles = StyleSheet.create({
done

2018-04-03 04:43 UTC, michaelnyu commented on src/screens/UserProfile.js
> +import { StackNavigator, } from 'react-navigation';
done

2018-04-03 04:45 UTC, michaelnyu commented on src/screens/UserProfile.js
> +			imageURL: 'https://pbs.twimg.com/profile_images/862164234947440640/WqQ358Yw_400x400.jpg',
done

2018-04-03 04:45 UTC, michaelnyu commented on src/screens/styles.js
> +import { Alert, DatePickerIOS, StyleSheet, Text, View, AppRegistry, Image, TextInput, Picker, Dimensions } from 'react-native';
done

2018-04-03 05:14 UTC, michaelnyu commented on src/screens/styles.js
> +import React from 'react';
removed entire file

2018-04-03 05:14 UTC, michaelnyu commented on src/screens/styles.js
> +
above

2018-04-03 05:14 UTC, michaelnyu commented on src/screens/styles.js
> +});
above

2018-04-03 05:14 UTC, michaelnyu commented on src/screens/styles/UserProfileStyle.js
> +	},
done

2018-04-03 05:52 UTC, epicchewy requested changes

2018-04-03 05:52 UTC, epicchewy commented on App.js
>  	Invite: {screen: InviteScreen },
space

2018-04-03 05:52 UTC, epicchewy commented on App.js
> +	UserProfile: { screen: UserProfile },
extra space

2018-04-03 05:52 UTC, epicchewy commented on data.js
> +const event_types = [
do you want to export this?

2018-04-03 05:52 UTC, epicchewy commented on package.json
> +    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
this is actually ok

2018-04-03 05:52 UTC, epicchewy commented on src/components/Button.js
> +} from 'react-native';
nit: alphabetical imports

2018-04-03 05:52 UTC, epicchewy commented on src/components/CardList.js
> +} from 'react-native';
nit: alphabetical

2018-04-03 05:52 UTC, epicchewy commented on src/screens/CreationScreen.js
> +	Picker,
nit: alphabetical import

2018-04-03 05:52 UTC, epicchewy commented on src/screens/CreationScreen.js
> +
remove new line

2018-04-03 05:52 UTC, epicchewy commented on src/screens/CreationScreen.js
> +import { CardList } from 'react-native-card-list';
add new line

2018-04-03 05:52 UTC, epicchewy commented on src/screens/HomeScreen.js
> +} from 'react-native';
nit: alphabetical importa

2018-04-03 05:52 UTC, epicchewy commented on src/screens/InviteScreen.js
> +} from 'react-native';
same as above

2018-04-03 05:52 UTC, epicchewy commented on src/screens/InviteScreen.js
> +} from 'react-native-elements';
same as above

2018-04-03 05:52 UTC, epicchewy commented on src/screens/InviteScreen.js
> +		const curMoment = moment(this.props.navigation.state.params.time).format("YYYY/DD/MM")
add ;

2018-04-03 05:52 UTC, epicchewy commented on src/screens/UserProfile.js
> +} from 'react-native';
same as above

2018-04-03 05:52 UTC, epicchewy commented on src/screens/styles/HomeScreenStyle.js
> +	flex: 1,
alignment

2018-04-03 05:52 UTC, epicchewy commented on src/screens/styles/HomeScreenStyle.js
> +	height: 40,
alignment

2018-04-03 05:52 UTC, epicchewy commented on src/screens/styles/UserProfileStyle.js
> +		button: {
alignment

2018-04-03 05:52 UTC, epicchewy commented on src/constants/styles.js
> +export const NAVY = '#072956';
add new lines between sections of styles (colors, fonts, etc)

2018-04-03 05:52 UTC, epicchewy commented on src/components/styles/ButtonStyle.js
> +		marginLeft: '25%',
seems hacky, is this the only way to ensure centered div?

2018-04-03 05:52 UTC, epicchewy commented on data.js
> +const event_types = [
rename file name to dummyData

2018-04-03 05:52 UTC, epicchewy commented on src/components/Button.js
> +import styles from './styles/ButtonStyle';
rename variable to buttonStyles

2018-04-03 05:52 UTC, epicchewy commented on src/components/Button.js
> +	const k = [styles.full];	//k is a list of styles for the outer <View>
rename k to styles, variable names should be descriptive

2018-04-03 05:52 UTC, epicchewy commented on src/components/styles/CardListStyle.js
> +		flex: .2,
alignment

2018-04-03 05:52 UTC, epicchewy commented on src/screens/EventScreen.js
> +			<View style={{ flex: 1,}}>
remove comma and add space

2018-04-03 06:23 UTC, michaelnyu commented on src/components/styles/ButtonStyle.js
> +		marginLeft: '25%',
it is hacky but it fit's our purpose pretty well as it takes care of centering both "full" and "half" sized Button's without having to change any styling on the button itself.  If I used flexbox, it would warrant adding extra styles to both the container and button which I thought would add too much complexity for maintainers.

But, if using flexbox and changing both the Button and Container are the way to go, let me know and i'll fix it

2018-04-03 07:11 UTC, epicchewy approved these changes

2018-04-03 15:03 UTC, merged